import { getPool } from "./integrations.js";
import { logger } from "./logger.js";

const statements = [
`CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, plan TEXT NOT NULL DEFAULT 'demo', status TEXT NOT NULL DEFAULT 'active', billing_email TEXT NOT NULL DEFAULT '', monthly_price_cents INTEGER NOT NULL DEFAULT 0, trial_ends_at TIMESTAMPTZ, access_ends_at TIMESTAMPTZ, billing_managed_past_due BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active'`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS billing_email TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS monthly_price_cents INTEGER NOT NULL DEFAULT 0`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS access_ends_at TIMESTAMPTZ`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS billing_managed_past_due BOOLEAN NOT NULL DEFAULT FALSE`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS is_platform_internal BOOLEAN NOT NULL DEFAULT FALSE`,
`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, must_change_password BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER NOT NULL DEFAULT 0`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS is_platform_admin BOOLEAN NOT NULL DEFAULT FALSE`,
`CREATE TABLE IF NOT EXISTS memberships (organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL, PRIMARY KEY (organization_id, user_id))`,
`CREATE TABLE IF NOT EXISTS venues (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, city TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', logo_url TEXT, theme JSONB NOT NULL DEFAULT '{}'::jsonb, modules JSONB NOT NULL DEFAULT '[]'::jsonb, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS zones (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, name TEXT NOT NULL, code TEXT NOT NULL, capacity INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(venue_id, code))`,
`CREATE TABLE IF NOT EXISTS experience_sessions (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', started_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS guest_sessions (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, zone_id TEXT REFERENCES zones(id) ON DELETE SET NULL, experience_session_id TEXT REFERENCES experience_sessions(id) ON DELETE SET NULL, nickname TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, connected BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), expires_at TIMESTAMPTZ NOT NULL)`,
`CREATE TABLE IF NOT EXISTS auth_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), expires_at TIMESTAMPTZ NOT NULL)`,
`ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE`,
`ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS user_agent TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
`UPDATE auth_sessions s SET organization_id=(SELECT m.organization_id FROM memberships m WHERE m.user_id=s.user_id ORDER BY m.organization_id LIMIT 1) WHERE s.organization_id IS NULL`,
`DELETE FROM auth_sessions WHERE organization_id IS NULL`,
`ALTER TABLE auth_sessions ALTER COLUMN organization_id SET NOT NULL`,
`UPDATE venues SET modules=modules || '["orders"]'::jsonb WHERE NOT (modules ? 'orders')`,
`CREATE TABLE IF NOT EXISTS music_items (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, experience_session_id TEXT REFERENCES experience_sessions(id) ON DELETE SET NULL, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, title TEXT NOT NULL, url TEXT NOT NULL, youtube_id TEXT, requested_by TEXT NOT NULL, zone_name TEXT, status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS music_votes (music_item_id TEXT NOT NULL REFERENCES music_items(id) ON DELETE CASCADE, guest_session_id TEXT NOT NULL REFERENCES guest_sessions(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(music_item_id, guest_session_id))`,
`CREATE TABLE IF NOT EXISTS playback_state (venue_id TEXT PRIMARY KEY REFERENCES venues(id) ON DELETE CASCADE, music_item_id TEXT REFERENCES music_items(id) ON DELETE SET NULL, video_id TEXT, state TEXT NOT NULL DEFAULT 'idle', "current_time" DOUBLE PRECISION NOT NULL DEFAULT 0, volume INTEGER NOT NULL DEFAULT 70, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS service_requests (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, zone_id TEXT REFERENCES zones(id) ON DELETE SET NULL, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, zone_name TEXT NOT NULL, guest_name TEXT NOT NULL, type TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'open', assigned_to TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), resolved_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS polls (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, question TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS poll_options (id TEXT PRIMARY KEY, poll_id TEXT NOT NULL REFERENCES polls(id) ON DELETE CASCADE, label TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0)`,
`CREATE TABLE IF NOT EXISTS poll_votes (poll_id TEXT NOT NULL REFERENCES polls(id) ON DELETE CASCADE, option_id TEXT NOT NULL REFERENCES poll_options(id) ON DELETE CASCADE, guest_session_id TEXT NOT NULL REFERENCES guest_sessions(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(poll_id, guest_session_id))`,
`CREATE TABLE IF NOT EXISTS quizzes (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', current_question_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS quiz_questions (id TEXT PRIMARY KEY, quiz_id TEXT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE, prompt TEXT NOT NULL, options JSONB NOT NULL, correct_index INTEGER NOT NULL, position INTEGER NOT NULL DEFAULT 0)`,
`CREATE TABLE IF NOT EXISTS quiz_answers (question_id TEXT NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE, guest_session_id TEXT NOT NULL REFERENCES guest_sessions(id) ON DELETE CASCADE, selected_index INTEGER NOT NULL, correct BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(question_id, guest_session_id))`,
`CREATE TABLE IF NOT EXISTS menu_categories (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, name TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0)`,
`CREATE TABLE IF NOT EXISTS menu_items (id TEXT PRIMARY KEY, category_id TEXT NOT NULL REFERENCES menu_categories(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price_cents INTEGER NOT NULL DEFAULT 0, image_url TEXT, available BOOLEAN NOT NULL DEFAULT TRUE, featured BOOLEAN NOT NULL DEFAULT FALSE)`,
`CREATE TABLE IF NOT EXISTS venue_orders (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, zone_id TEXT REFERENCES zones(id) ON DELETE SET NULL, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, zone_name TEXT NOT NULL, guest_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', note TEXT NOT NULL DEFAULT '', total_cents INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES venue_orders(id) ON DELETE CASCADE, menu_item_id TEXT REFERENCES menu_items(id) ON DELETE SET NULL, name TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price_cents INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS venue_events (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, capacity INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS reservations (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES venue_events(id) ON DELETE CASCADE, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, guest_name TEXT NOT NULL, contact TEXT NOT NULL, party_size INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'confirmed', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`ALTER TABLE reservations ADD COLUMN IF NOT EXISTS guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL`,
`CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', code TEXT NOT NULL, reward TEXT NOT NULL, starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(venue_id, code))`,
`CREATE TABLE IF NOT EXISTS coupon_redemptions (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE, customer_key TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(campaign_id, customer_key))`,
`CREATE TABLE IF NOT EXISTS loyalty_accounts (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, customer_key TEXT NOT NULL, display_name TEXT NOT NULL, points INTEGER NOT NULL DEFAULT 0, level TEXT NOT NULL DEFAULT 'visitor', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(venue_id, customer_key))`,
`CREATE TABLE IF NOT EXISTS loyalty_transactions (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES loyalty_accounts(id) ON DELETE CASCADE, points INTEGER NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS media_posts (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, guest_name TEXT NOT NULL, image_url TEXT NOT NULL, storage_key TEXT NOT NULL, caption TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS feedback (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, guest_session_id TEXT REFERENCES guest_sessions(id) ON DELETE SET NULL, score INTEGER NOT NULL CHECK(score BETWEEN 1 AND 5), comment TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS announcements (id TEXT PRIMARY KEY, venue_id TEXT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, title TEXT NOT NULL, body TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'info', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS audit_logs (id BIGSERIAL PRIMARY KEY, organization_id TEXT, user_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, details JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS request_id TEXT`,
`ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_hash TEXT`,
`CREATE TABLE IF NOT EXISTS billing_invoices (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, reference TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>=0), due_at TIMESTAMPTZ NOT NULL, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'open', paid_at TIMESTAMPTZ, payment_method TEXT NOT NULL DEFAULT '', external_reference TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(organization_id, reference))`,
`ALTER TABLE billing_invoices ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE billing_invoices ADD COLUMN IF NOT EXISTS external_reference TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE billing_invoices ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE billing_invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
`CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_org ON auth_sessions(user_id, organization_id, expires_at)`,
`CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_seen ON auth_sessions(user_id, last_seen_at DESC)`,
`CREATE INDEX IF NOT EXISTS idx_users_locked_until ON users(locked_until) WHERE locked_until IS NOT NULL`,
`CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires ON auth_sessions(expires_at)`,
`CREATE INDEX IF NOT EXISTS idx_guest_sessions_expires ON guest_sessions(expires_at)`,
`CREATE INDEX IF NOT EXISTS idx_organizations_status ON organizations(status, trial_ends_at, access_ends_at)`,
`CREATE INDEX IF NOT EXISTS idx_organizations_platform_internal ON organizations(is_platform_internal,created_at DESC)`,
`CREATE INDEX IF NOT EXISTS idx_guest_venue ON guest_sessions(venue_id, expires_at)`,
`CREATE INDEX IF NOT EXISTS idx_music_venue ON music_items(venue_id, status, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_requests_venue ON service_requests(venue_id, status, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_orders_venue ON venue_orders(venue_id, status, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_reservations_guest_event ON reservations(event_id, guest_session_id, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_quizzes_venue ON quizzes(venue_id, status, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_feedback_venue ON feedback(venue_id, created_at)`,
`CREATE INDEX IF NOT EXISTS idx_audit_org_id ON audit_logs(organization_id, id DESC)`,
`CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at)`,
`CREATE INDEX IF NOT EXISTS idx_billing_org_due ON billing_invoices(organization_id, status, due_at DESC)`,
`CREATE INDEX IF NOT EXISTS idx_billing_overdue ON billing_invoices(status, due_at) WHERE status IN ('open','overdue')`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS max_venues INTEGER`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS max_users INTEGER`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS max_zones_per_venue INTEGER`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS require_guest_consent BOOLEAN NOT NULL DEFAULT FALSE`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS privacy_policy_url TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS terms_url TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS privacy_version TEXT NOT NULL DEFAULT '1.0'`,
`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS terms_version TEXT NOT NULL DEFAULT '1.0'`,
`ALTER TABLE guest_sessions ADD COLUMN IF NOT EXISTS accepted_privacy_at TIMESTAMPTZ`,
`ALTER TABLE guest_sessions ADD COLUMN IF NOT EXISTS accepted_terms_at TIMESTAMPTZ`,
`ALTER TABLE guest_sessions ADD COLUMN IF NOT EXISTS privacy_version TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE guest_sessions ADD COLUMN IF NOT EXISTS terms_version TEXT NOT NULL DEFAULT ''`,
`CREATE TABLE IF NOT EXISTS admin_notifications (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, kind TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'info', entity_type TEXT, entity_id TEXT, dedupe_key TEXT, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe ON admin_notifications(organization_id,dedupe_key) WHERE dedupe_key IS NOT NULL`,
`CREATE INDEX IF NOT EXISTS idx_notifications_org_unread ON admin_notifications(organization_id,read_at,created_at DESC)`,
`UPDATE organizations SET require_guest_consent=FALSE WHERE id='org_demo'`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret_encrypted TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enrolled_at TIMESTAMPTZ`,
`ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS mfa_verified_at TIMESTAMPTZ`,
`ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS step_up_at TIMESTAMPTZ`,
`CREATE TABLE IF NOT EXISTS mfa_recovery_codes (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, code_hash TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS mfa_challenges (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, mode TEXT NOT NULL, secret_encrypted TEXT NOT NULL DEFAULT '', attempts INTEGER NOT NULL DEFAULT 0, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE INDEX IF NOT EXISTS idx_mfa_challenges_expiry ON mfa_challenges(expires_at)`,
`CREATE TABLE IF NOT EXISTS security_events (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE, event_type TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'info', details JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE INDEX IF NOT EXISTS idx_security_events_org_created ON security_events(organization_id,created_at DESC)`,
`CREATE INDEX IF NOT EXISTS idx_security_events_type_created ON security_events(event_type,created_at DESC)`,
`ALTER TABLE media_posts ADD COLUMN IF NOT EXISTS scan_status TEXT NOT NULL DEFAULT 'clean'`,
`ALTER TABLE media_posts ADD COLUMN IF NOT EXISTS scan_engine TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE media_posts ADD COLUMN IF NOT EXISTS scan_details TEXT NOT NULL DEFAULT ''`,
`ALTER TABLE media_posts ADD COLUMN IF NOT EXISTS scanned_at TIMESTAMPTZ`,
`CREATE INDEX IF NOT EXISTS idx_media_scan_status ON media_posts(scan_status,created_at)`,
`CREATE TABLE IF NOT EXISTS idempotency_keys (scope TEXT NOT NULL, key_hash TEXT NOT NULL, response_status INTEGER NOT NULL, response_body JSONB NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(scope,key_hash))`,
`CREATE INDEX IF NOT EXISTS idx_idempotency_expiry ON idempotency_keys(expires_at)`,
`CREATE TABLE IF NOT EXISTS password_reset_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE INDEX IF NOT EXISTS idx_password_reset_expiry ON password_reset_tokens(expires_at)`,
`CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id,created_at DESC)`
];
export async function migrate(): Promise<void> {
  const client = await getPool().connect();
  try {
    await client.query("BEGIN");
    await client.query(`SELECT pg_advisory_xact_lock(hashtext('vibevenue:migrations'))`);
    for (const statement of statements) await client.query(statement);
    await client.query("COMMIT");
    logger.info({ statements: statements.length }, "Migrações aplicadas");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally { client.release(); }
}
