"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import type { AdminIdentity,AdminSnapshot,MusicItem,OrganizationAccess,Venue,VenueModule } from "@vibevenue/contracts";
import { BarChart3,Bell,Building2,CalendarDays,Check,ChevronRight,ClipboardList,Headphones,ImageIcon,LayoutDashboard,LogOut,MapPin,MonitorPlay,RefreshCw,Settings,ShieldCheck,ShoppingBag,Star,Ticket,Trophy,Users,X } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { ApiError,api,assetUrl } from "@/lib/api";
import { useRealtime } from "@/hooks/use-realtime";
import { Badge,Button,Card,Empty,Field,Metric,Select,Textarea } from "./ui";
import { YouTubePlayer } from "./youtube-player";
import { AccountSettings, PasswordChangeGate } from "./account-settings";
import { PlatformConsole } from "./platform-console";

type Tab="overview"|"music"|"service"|"orders"|"engagement"|"events"|"media"|"insights"|"settings";
const tabs:[Tab,string,typeof LayoutDashboard][]=[["overview","Visão geral",LayoutDashboard],["music","Música",Headphones],["service","Atendimento",ClipboardList],["orders","Pedidos",ShoppingBag],["engagement","Interação",Trophy],["events","Eventos",CalendarDays],["media","Mural",ImageIcon],["insights","Métricas",BarChart3],["settings","Configurações",Settings]];
const roleTabs:Record<AdminIdentity["role"],Tab[]>={owner:tabs.map(([id])=>id),manager:tabs.map(([id])=>id),operator:["overview","music","service","orders","insights","settings"],moderator:["overview","music","media","insights","settings"],marketing:["overview","engagement","events","media","insights","settings"],viewer:["overview","insights","settings"]};
const tabModules:Partial<Record<Tab,VenueModule[]>>={music:["music"],service:["service"],orders:["orders"],engagement:["polls","quiz","signage"],events:["events","campaigns"],media:["media"],insights:["analytics"]};
const allModules:VenueModule[]=["music","service","orders","polls","quiz","events","loyalty","campaigns","media","feedback","signage","analytics"];
const localDateTimeToIso=(value:string)=>new Date(value).toISOString();
function statusTone(status:string):"purple"|"cyan"|"green"|"amber"|"red"{if(["approved","playing","resolved","active","published","live"].includes(status))return"green";if(["pending","open","assigned","draft"].includes(status))return"amber";if(["rejected","cancelled","ended"].includes(status))return"red";return"purple"}
export function AdminDashboard({onLogout,onError,onSuccess}:{onLogout:()=>void;onError:(v:string)=>void;onSuccess:(v:string)=>void}){
 const[identity,setIdentity]=useState<AdminIdentity|null>(null);const[organization,setOrganization]=useState<OrganizationAccess|null>(null);const[venues,setVenues]=useState<Venue[]>([]);const[venueId,setVenueId]=useState("");const[snapshot,setSnapshot]=useState<AdminSnapshot|null>(null);const[tab,setTab]=useState<Tab>("overview");const[busy,setBusy]=useState(false);const[menu,setMenu]=useState(false);
 const refresh=useCallback(async()=>{try{const me=await api.adminMe();setIdentity(me.identity);setOrganization(me.organization);setVenues(me.venues);if(me.identity.mustChangePassword){setSnapshot(null);return}const selected=venueId||me.venues[0]?.id||"";if(selected){if(!venueId)setVenueId(selected);const data=await api.adminSnapshot(selected);setSnapshot(data.snapshot)}else setSnapshot(null)}catch(error){if(error instanceof ApiError&&error.status===401){onLogout();return}onError(error instanceof Error?error.message:"Falha ao atualizar painel")}},[venueId,onError,onLogout]);
 useEffect(()=>{void refresh()},[refresh]);useRealtime({venueId:snapshot?.venue.id,admin:true,onUpdate:refresh});
 const act=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);try{await fn();await refresh();onSuccess(success)}catch(error){onError(error instanceof Error?error.message:"Ação não concluída")}finally{setBusy(false)}};
 const logout=()=>{void api.logout().finally(onLogout)};
 if(identity?.mustChangePassword)return <PasswordChangeGate identity={identity} onError={onError} onSuccess={onSuccess} onChanged={()=>void refresh()} onLogout={logout}/>;
 if(identity?.isPlatformAdmin)return <PlatformConsole identity={identity} onLogout={logout} onError={onError} onSuccess={onSuccess}/>;
 if(!snapshot||!identity)return <main className="loading-page"><span className="logo-mark large">V</span><p>Preparando o painel...</p></main>;
 const enabledModules=new Set(snapshot.venue.modules);
 const visibleTabs=tabs.filter(([id])=>(roleTabs[identity.role]??[]).includes(id)&&(tabModules[id]?.some(module=>enabledModules.has(module))??true));
 const activeTab=visibleTabs.some(([id])=>id===tab)?tab:(visibleTabs[0]?.[0]??"overview");
 return <main className="admin-layout"><aside className={menu?"sidebar open":"sidebar"}><div className="sidebar-brand"><span className="logo-mark">V</span><div><strong>VibeVenue</strong><small>BUSINESS</small></div><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button></div><div className="venue-picker"><span>Estabelecimento</span><Select value={venueId} onChange={e=>setVenueId(e.target.value)}>{venues.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</Select></div><nav>{visibleTabs.map(([id,label,Icon])=><button key={id} className={activeTab===id?"active":""} onClick={()=>{setTab(id);setMenu(false)}}><Icon size={19}/><span>{label}</span>{activeTab===id&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-user"><div className="user-avatar">{identity.name.slice(0,1)}</div><div><strong>{identity.name}</strong><small>{identity.role}</small></div><button onClick={logout} aria-label="Sair"><LogOut/></button></div></aside><section className="admin-main"><header className="admin-top"><button className="mobile-menu" onClick={()=>setMenu(true)}>☰</button><div><span className="eyebrow">{snapshot.venue.city}</span><h1>{visibleTabs.find(([id])=>id===activeTab)?.[1]??"Painel"}</h1></div><div className="top-actions"><span className="live-pill"><i/> Sistema online</span><Button variant="ghost" onClick={()=>void refresh()}><RefreshCw size={17}/> Atualizar</Button></div></header><div className="admin-content">
 {activeTab==="overview"&&<Overview snapshot={snapshot} setTab={setTab}/>} 
 {activeTab==="music"&&<Music snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="service"&&<Service snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="orders"&&<Orders snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="engagement"&&<Engagement snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="events"&&<Events snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="media"&&<Media snapshot={snapshot} busy={busy} act={act}/>} 
 {activeTab==="insights"&&<Insights snapshot={snapshot}/>} 
 {activeTab==="settings"&&<><AccountSettings identity={identity} organization={organization} onOrganizationChanged={setOrganization} onError={onError} onSuccess={onSuccess}/><Configuration snapshot={snapshot} busy={busy} act={act} canManage={["owner","manager"].includes(identity.role)}/></>} 
 </div></section></main>
}
function Overview({snapshot,setTab}:{snapshot:AdminSnapshot;setTab:(tab:Tab)=>void}){
 const m=snapshot.metrics;
 return <div className="stack-lg"><section className="metric-grid"><Metric label="Clientes ativos" value={m.activeGuests} detail="sessões nas últimas 12h"/><Metric label="Atendimentos" value={m.openRequests} detail="aguardando equipe"/><Metric label="Pedidos comerciais" value={m.pendingOrders} detail="em produção ou entrega"/><Metric label="Satisfação" value={m.feedbackScore.toFixed(1)} detail="média de 5 pontos"/></section><div className="admin-grid wide"><Card title="Operação agora" action={<Button variant="ghost" onClick={()=>setTab("service")}>Abrir operação</Button>}><div className="operation-list"><Operation icon={<ClipboardList/>} title="Solicitações" value={`${m.openRequests} pendentes`} tone="amber"/><Operation icon={<ShoppingBag/>} title="Pedidos" value={`${m.pendingOrders} ativos`} tone="green"/><Operation icon={<Headphones/>} title="Playlist" value={`${snapshot.allMusic.filter(item=>item.status==='approved').length} aprovadas`} tone="cyan"/><Operation icon={<Users/>} title="Participação" value={`${m.interactionsToday} interações hoje`} tone="purple"/></div></Card><Card title="Reprodução atual"><YouTubePlayer playback={snapshot.playback}/><div className="now-playing"><strong>{snapshot.allMusic.find(item=>item.id===snapshot.playback.itemId)?.title??"Nenhuma música iniciada"}</strong><Badge tone={snapshot.playback.state==="playing"?"green":"purple"}>{snapshot.playback.state}</Badge></div></Card></div><div className="admin-grid"><Card title="Atividade por área">{m.topZones.length?m.topZones.map(zone=><div className="bar-row" key={zone.name}><span>{zone.name}</span><div><i style={{width:`${Math.max(8,zone.value/Math.max(...m.topZones.map(item=>item.value))*100)}%`}}/></div><strong>{zone.value}</strong></div>):<Empty>Ainda não há entradas registradas.</Empty>}</Card><Card title="Próximos eventos">{snapshot.events.length?snapshot.events.slice(0,4).map(event=><div className="compact-row" key={event.id}><CalendarDays/><div><strong>{event.title}</strong><small>{new Date(event.startsAt).toLocaleString("pt-BR")}</small></div><Badge tone="cyan">{event.reservations} reservas</Badge></div>):<Empty>Nenhum evento publicado.</Empty>}</Card><Card title="Campanhas ativas">{snapshot.campaigns.length?snapshot.campaigns.map(campaign=><div className="compact-row" key={campaign.id}><Ticket/><div><strong>{campaign.title}</strong><small>{campaign.reward}</small></div><Badge tone="green">{campaign.code}</Badge></div>):<Empty>Nenhuma campanha ativa.</Empty>}</Card></div></div>
}
function Operation({icon,title,value,tone}:{icon:React.ReactNode;title:string;value:string;tone:string}){return <div className={`operation ${tone}`}><span>{icon}</span><div><strong>{title}</strong><small>{value}</small></div></div>}
function Music({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(f:()=>Promise<unknown>,s:string)=>Promise<void>}){const[current,setCurrent]=useState(snapshot.playback);useEffect(()=>setCurrent(snapshot.playback),[snapshot.playback]);const items=snapshot.allMusic;const update=(item:MusicItem,status:string)=>act(()=>api.musicStatus(snapshot.venue.id,item.id,status),`Música atualizada para ${status}.`);const control=(state:"playing"|"paused"|"idle")=>act(()=>api.playback(snapshot.venue.id,{...current,state}),"Reprodução sincronizada.");return <div className="admin-grid wide"><Card title="Player do estabelecimento"><YouTubePlayer playback={current}/><div className="player-controls"><Button onClick={()=>control("playing")}>▶ Reproduzir</Button><Button variant="secondary" onClick={()=>control("paused")}>⏸ Pausar</Button><Button variant="ghost" onClick={()=>control("idle")}>■ Parar</Button></div><label>Volume: {current.volume}%<input className="range" type="range" min="0" max="100" value={current.volume} onChange={e=>setCurrent({...current,volume:Number(e.target.value)})} onMouseUp={()=>void act(()=>api.playback(snapshot.venue.id,current),"Volume atualizado.")}/></label><p className="muted small">A TV reproduz o vídeo. Os celulares acompanham fila, votos e pedidos sem gerar eco.</p></Card><Card title={`Fila musical (${items.length})`} className="span-two"><div className="table-list">{items.length?items.map(item=><div className="music-row" key={item.id}><div className="music-thumb">{item.youtubeId?<img src={`https://i.ytimg.com/vi/${item.youtubeId}/mqdefault.jpg`} alt=""/>:<Headphones/>}</div><div className="grow"><strong>{item.title}</strong><small>{item.requestedBy}{item.zoneName?` • ${item.zoneName}`:""} • {item.votes} votos</small></div><Badge tone={statusTone(item.status)}>{item.status}</Badge><div className="row-actions">{item.status==="pending"&&<><Button disabled={busy} onClick={()=>void update(item,"approved")}><Check/> Aprovar</Button><Button variant="danger" disabled={busy} onClick={()=>void update(item,"rejected")}><X/> Rejeitar</Button></>}{item.status==="approved"&&<Button disabled={busy} onClick={()=>void update(item,"playing")}>▶ Tocar agora</Button>}{item.status==="playing"&&<Button variant="secondary" disabled={busy} onClick={()=>void update(item,"played")}>Marcar tocada</Button>}</div></div>):<Empty>Os pedidos enviados pelos clientes aparecerão aqui.</Empty>}</div></Card></div>}
function Service({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(fn:()=>Promise<unknown>,success:string)=>Promise<void>}){
 return <Card title={`Central de atendimento (${snapshot.serviceRequests.length})`}><div className="table-list">{snapshot.serviceRequests.length?snapshot.serviceRequests.map(item=><div className="request-row" key={item.id}><div className={`request-icon ${item.priority}`}><Bell/></div><div className="grow"><div className="title-line"><strong>{item.zoneName} • {item.guestName}</strong><Badge tone={statusTone(item.status)}>{item.status}</Badge></div><p>{item.type.replaceAll("_"," ")}{item.note?` — ${item.note}`:""}</p><small>{new Date(item.createdAt).toLocaleString("pt-BR")}{item.assignedTo?` • ${item.assignedTo}`:""}</small></div><div className="row-actions">{item.status==="open"&&<Button disabled={busy} onClick={()=>void act(()=>api.serviceStatus(snapshot.venue.id,item.id,"assigned"),"Atendimento assumido.")}>Assumir</Button>}{item.status!=="resolved"&&item.status!=="cancelled"&&<Button variant="secondary" disabled={busy} onClick={()=>void act(()=>api.serviceStatus(snapshot.venue.id,item.id,"resolved"),"Solicitação resolvida.")}>Resolver</Button>}</div></div>):<Empty>Nenhuma solicitação recebida.</Empty>}</div></Card>
}
function Orders({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(fn:()=>Promise<unknown>,success:string)=>Promise<void>}){
 const next:Record<string,string>={new:"accepted",accepted:"preparing",preparing:"ready",ready:"delivered"};
 const label:Record<string,string>={new:"Aceitar",accepted:"Preparar",preparing:"Marcar pronto",ready:"Entregar"};
 const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value/100);
 return <Card title={`Pedidos por QR Code (${snapshot.orders.length})`}><div className="table-list">{snapshot.orders.length?snapshot.orders.map(order=><div className="request-row" key={order.id}><div className="request-icon normal"><ShoppingBag/></div><div className="grow"><div className="title-line"><strong>{order.zoneName} • {order.guestName}</strong><Badge tone={statusTone(order.status)}>{order.status}</Badge></div><p>{order.items.map(item=>`${item.quantity}× ${item.name}`).join(" • ")}</p><small>{money(order.totalCents)} • {new Date(order.createdAt).toLocaleString("pt-BR")}{order.note?` • ${order.note}`:""}</small></div><div className="row-actions">{next[order.status]&&<Button disabled={busy} onClick={()=>void act(()=>api.orderStatus(snapshot.venue.id,order.id,next[order.status]!),"Status do pedido atualizado.")}>{label[order.status]}</Button>}{!['delivered','cancelled'].includes(order.status)&&<Button variant="danger" disabled={busy} onClick={()=>void act(()=>api.orderStatus(snapshot.venue.id,order.id,"cancelled"),"Pedido cancelado.")}>Cancelar</Button>}</div></div>):<Empty>Nenhum pedido recebido.</Empty>}</div></Card>
}
function Engagement({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(fn:()=>Promise<unknown>,success:string)=>Promise<void>}){
 const[q,setQ]=useState("");const[o,setO]=useState("Opção A\nOpção B");const[title,setTitle]=useState("");const[body,setBody]=useState("");
 const[quiz,setQuiz]=useState({title:"Quiz da casa",prompt:"",options:"Resposta A\nResposta B\nResposta C",correctIndex:0});
 const options=o.split("\n").map(value=>value.trim()).filter(Boolean);
 const quizOptions=quiz.options.split("\n").map(value=>value.trim()).filter(Boolean);
 return <div className="admin-grid"><Card title="Nova enquete"><div className="form-stack"><label>Pergunta<Field value={q} onChange={event=>setQ(event.target.value)} placeholder="O que o público deve escolher?"/></label><label>Opções, uma por linha<Textarea value={o} onChange={event=>setO(event.target.value)}/></label><Button disabled={busy||q.length<2||options.length<2} onClick={()=>void act(()=>api.createPoll(snapshot.venue.id,q,options),"Enquete publicada.")}>Publicar enquete</Button></div></Card><Card title="Novo quiz ao vivo"><div className="form-stack"><Field value={quiz.title} onChange={event=>setQuiz({...quiz,title:event.target.value})} placeholder="Título do quiz"/><Textarea value={quiz.prompt} onChange={event=>setQuiz({...quiz,prompt:event.target.value})} placeholder="Pergunta"/><label>Respostas, uma por linha<Textarea value={quiz.options} onChange={event=>setQuiz({...quiz,options:event.target.value})}/></label><label>Resposta correta<Select value={quiz.correctIndex} onChange={event=>setQuiz({...quiz,correctIndex:Number(event.target.value)})}>{quizOptions.map((option,index)=><option value={index} key={`${option}-${index}`}>{String.fromCharCode(65+index)} — {option}</option>)}</Select></label><Button disabled={busy||quiz.prompt.length<2||quizOptions.length<2} onClick={()=>void act(()=>api.createQuiz(snapshot.venue.id,{title:quiz.title,prompt:quiz.prompt,options:quizOptions,correctIndex:quiz.correctIndex}),"Quiz publicado.")}>Publicar quiz</Button></div></Card><Card title="Comunicado para TV e celulares"><div className="form-stack"><label>Título<Field value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Mensagem<Textarea value={body} onChange={event=>setBody(event.target.value)}/></label><Button disabled={busy||!title||!body} onClick={()=>void act(()=>api.announcement(snapshot.venue.id,{title,body,kind:"info"}),"Comunicado publicado.")}>Publicar comunicado</Button></div></Card><Card title="Resultado da enquete atual">{snapshot.poll?snapshot.poll.options.map(option=><div className="poll-result" key={option.id}><span>{option.label}</span><div><i style={{width:`${snapshot.poll?.totalVotes?option.votes/snapshot.poll.totalVotes*100:0}%`}}/></div><strong>{option.votes}</strong></div>):<Empty>Nenhuma enquete ao vivo.</Empty>}</Card><Card title="Quiz atual" className="span-two">{snapshot.quiz?.currentQuestion?<div className="settings-callout"><Trophy/><div><strong>{snapshot.quiz.title}</strong><p>{snapshot.quiz.currentQuestion.prompt}</p><small>{snapshot.quiz.currentQuestion.answers} respostas recebidas</small></div><Badge tone="green">ao vivo</Badge></div>:<Empty>Nenhum quiz ao vivo.</Empty>}</Card></div>
}
function Events({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(f:()=>Promise<unknown>,s:string)=>Promise<void>}){const[event,setEvent]=useState({title:"",description:"",startsAt:"",endsAt:"",capacity:100});const[campaign,setCampaign]=useState({title:"",description:"",code:"",reward:"",startsAt:"",endsAt:""});return <div className="admin-grid"><Card title="Criar evento"><div className="form-stack"><Field placeholder="Nome do evento" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/><Textarea placeholder="Descrição" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><label>Início<Field type="datetime-local" value={event.startsAt} onChange={e=>setEvent({...event,startsAt:e.target.value})}/></label><label>Término<Field type="datetime-local" value={event.endsAt} onChange={e=>setEvent({...event,endsAt:e.target.value})}/></label><Field type="number" min="0" value={event.capacity} onChange={e=>setEvent({...event,capacity:Number(e.target.value)})}/><Button disabled={busy||!event.title||!event.startsAt||!event.endsAt} onClick={()=>void act(()=>api.createEvent(snapshot.venue.id,{...event,startsAt:localDateTimeToIso(event.startsAt),endsAt:localDateTimeToIso(event.endsAt)}),"Evento publicado.")}>Criar evento</Button></div></Card><Card title="Criar campanha"><div className="form-stack"><Field placeholder="Título" value={campaign.title} onChange={e=>setCampaign({...campaign,title:e.target.value})}/><Textarea placeholder="Descrição" value={campaign.description} onChange={e=>setCampaign({...campaign,description:e.target.value})}/><Field placeholder="Código do cupom" value={campaign.code} onChange={e=>setCampaign({...campaign,code:e.target.value.toUpperCase()})}/><Field placeholder="Recompensa" value={campaign.reward} onChange={e=>setCampaign({...campaign,reward:e.target.value})}/><label>Início<Field type="datetime-local" value={campaign.startsAt} onChange={e=>setCampaign({...campaign,startsAt:e.target.value})}/></label><label>Término<Field type="datetime-local" value={campaign.endsAt} onChange={e=>setCampaign({...campaign,endsAt:e.target.value})}/></label><Button disabled={busy||!campaign.title||!campaign.code||!campaign.startsAt||!campaign.endsAt} onClick={()=>void act(()=>api.createCampaign(snapshot.venue.id,{...campaign,startsAt:localDateTimeToIso(campaign.startsAt),endsAt:localDateTimeToIso(campaign.endsAt)}),"Campanha publicada.")}>Criar campanha</Button></div></Card><Card title="Eventos cadastrados" className="span-two">{snapshot.allEvents.map(e=><div className="compact-row" key={e.id}><CalendarDays/><div><strong>{e.title}</strong><small>{new Date(e.startsAt).toLocaleString("pt-BR")} • capacidade {e.capacity}</small></div><Badge tone={statusTone(e.status)}>{e.reservations} reservas</Badge></div>)}</Card></div>}
function Media({snapshot,busy,act}:{snapshot:AdminSnapshot;busy:boolean;act:(f:()=>Promise<unknown>,s:string)=>Promise<void>}){return <div className="stack-lg"><Card title={`Aguardando moderação (${snapshot.pendingMedia.length})`}><div className="media-grid">{snapshot.pendingMedia.length?snapshot.pendingMedia.map(post=><figure className="media-card" key={post.id}><img src={assetUrl(post.imageUrl)} alt={post.caption}/><figcaption><strong>{post.guestName}</strong><p>{post.caption||"Sem legenda"}</p><div><Button disabled={busy} onClick={()=>void act(()=>api.mediaStatus(snapshot.venue.id,post.id,"approved"),"Foto aprovada.")}>Aprovar</Button><Button variant="danger" disabled={busy} onClick={()=>void act(()=>api.mediaStatus(snapshot.venue.id,post.id,"rejected"),"Foto rejeitada.")}>Rejeitar</Button></div></figcaption></figure>):<Empty>Não há fotos aguardando aprovação.</Empty>}</div></Card><Card title="Mural exibido na TV"><div className="media-grid compact">{snapshot.media.map(post=><figure className="media-card" key={post.id}><img src={assetUrl(post.imageUrl)} alt={post.caption}/><figcaption><strong>{post.guestName}</strong><p>{post.caption}</p></figcaption></figure>)}</div></Card></div>}
function Insights({snapshot}:{snapshot:AdminSnapshot}){const scores=useMemo(()=>[1,2,3,4,5].map(score=>({score,count:snapshot.feedback.filter(f=>f.score===score).length})),[snapshot.feedback]);return <div className="admin-grid"><Card title="Indicadores"><div className="metric-grid inside"><Metric label="Interações hoje" value={snapshot.metrics.interactionsToday}/><Metric label="Clientes fidelizados" value={snapshot.loyalty.length}/><Metric label="Conteúdos no mural" value={snapshot.metrics.approvedMedia}/><Metric label="Próximas reservas" value={snapshot.allEvents.reduce((a,e)=>a+e.reservations,0)}/></div></Card><Card title="Distribuição de satisfação">{scores.map(item=><div className="bar-row" key={item.score}><span>{item.score} estrelas</span><div><i style={{width:`${snapshot.feedback.length?item.count/snapshot.feedback.length*100:0}%`}}/></div><strong>{item.count}</strong></div>)}</Card><Card title="Últimos comentários" className="span-two">{snapshot.feedback.length?snapshot.feedback.map(f=><div className="feedback-row" key={f.id}><div>{Array.from({length:f.score}).map((_,i)=><Star key={i} size={15} fill="currentColor"/>)}</div><p>{f.comment||"Avaliação sem comentário"}</p><small>{new Date(f.createdAt).toLocaleString("pt-BR")}</small></div>):<Empty>Ainda não há avaliações.</Empty>}</Card><Card title="Ranking de fidelidade" className="span-two">{snapshot.loyalty.map((a,index)=><div className="compact-row" key={a.id}><span className="rank">{index+1}</span><div><strong>{a.displayName}</strong><small>{a.level}</small></div><Badge tone="purple">{a.points} pontos</Badge></div>)}</Card></div>}
function ZoneSettings({venueId,zone,busy,act}:{venueId:string;zone:AdminSnapshot["zones"][number];busy:boolean;act:(fn:()=>Promise<unknown>,success:string)=>Promise<void>}){
 const[value,setValue]=useState({name:zone.name,code:zone.code,capacity:zone.capacity,isActive:zone.isActive});
 useEffect(()=>setValue({name:zone.name,code:zone.code,capacity:zone.capacity,isActive:zone.isActive}),[zone]);
 return <div className="zone-settings"><Field value={value.name} onChange={event=>setValue({...value,name:event.target.value})}/><Field value={value.code} onChange={event=>setValue({...value,code:event.target.value.toUpperCase()})}/><Field type="number" min="0" value={value.capacity} onChange={event=>setValue({...value,capacity:Number(event.target.value)})}/><label className="check-line"><input type="checkbox" checked={value.isActive} onChange={event=>setValue({...value,isActive:event.target.checked})}/> Área ativa</label><Button variant="secondary" disabled={busy||value.name.length<2||value.code.length<2} onClick={()=>void act(()=>api.updateZone(venueId,zone.id,value),"Área atualizada.")}>Salvar área</Button></div>
}
function Configuration({snapshot,busy,act,canManage}:{snapshot:AdminSnapshot;busy:boolean;act:(fn:()=>Promise<unknown>,success:string)=>Promise<void>;canManage:boolean}){
 const base=typeof window!=="undefined"?window.location.origin:"";
 const[zone,setZone]=useState({name:"",code:"",capacity:0});
 const[newVenue,setNewVenue]=useState({name:"",city:"",description:""});
 const[current,setCurrent]=useState({name:snapshot.venue.name,city:snapshot.venue.city,description:snapshot.venue.description,modules:snapshot.venue.modules});
 useEffect(()=>setCurrent({name:snapshot.venue.name,city:snapshot.venue.city,description:snapshot.venue.description,modules:snapshot.venue.modules}),[snapshot.venue]);
 const toggleModule=(module:VenueModule)=>setCurrent({...current,modules:current.modules.includes(module)?current.modules.filter(item=>item!==module):[...current.modules,module]});
 return <div className="stack-lg">
  <Card title="QR Codes por área"><p className="muted">Imprima um QR diferente em cada mesa, setor ou ambiente. O sistema identifica automaticamente de onde veio cada solicitação.</p><div className="qr-grid">{snapshot.zones.map(item=>{const url=`${base}/?venue=${snapshot.venue.slug}&zone=${item.code}`;return <div className="qr-card" key={item.id}><QRCodeSVG value={url} size={150} bgColor="transparent" fgColor="#ffffff"/><strong>{item.name}</strong><Badge tone={item.isActive?"cyan":"red"}>{item.code}</Badge><small>{url}</small></div>})}</div></Card>
  {canManage&&<><Card title="Editar estabelecimento"><div className="form-stack"><Field value={current.name} onChange={event=>setCurrent({...current,name:event.target.value})} placeholder="Nome"/><Field value={current.city} onChange={event=>setCurrent({...current,city:event.target.value})} placeholder="Cidade"/><Textarea value={current.description} onChange={event=>setCurrent({...current,description:event.target.value})} placeholder="Descrição"/><div className="module-grid selectable">{allModules.map(module=><button type="button" className={current.modules.includes(module)?"selected":""} key={module} onClick={()=>toggleModule(module)}><ShieldCheck/><span>{module}</span><Badge tone={current.modules.includes(module)?"green":"purple"}>{current.modules.includes(module)?"ativo":"inativo"}</Badge></button>)}</div><Button disabled={busy||current.name.length<2||current.modules.length<1} onClick={()=>void act(()=>api.updateVenue(snapshot.venue.id,current),"Estabelecimento atualizado.")}>Salvar unidade e módulos</Button></div></Card>
  <Card title="Gerenciar áreas"><div className="form-stack">{snapshot.zones.map(item=><ZoneSettings key={item.id} venueId={snapshot.venue.id} zone={item} busy={busy} act={act}/>)}</div></Card>
  <div className="admin-grid"><Card title="Adicionar área ou mesa"><div className="form-stack"><Field value={zone.name} onChange={event=>setZone({...zone,name:event.target.value})} placeholder="Nome da área"/><Field value={zone.code} onChange={event=>setZone({...zone,code:event.target.value.toUpperCase()})} placeholder="Código do QR"/><Field type="number" min="0" value={zone.capacity} onChange={event=>setZone({...zone,capacity:Number(event.target.value)})}/><Button disabled={busy||zone.name.length<2||zone.code.length<2} onClick={()=>void act(()=>api.createZone(snapshot.venue.id,zone),"Área criada e QR disponibilizado.")}><MapPin/> Criar área</Button></div></Card><Card title="Adicionar estabelecimento"><div className="form-stack"><Field value={newVenue.name} onChange={event=>setNewVenue({...newVenue,name:event.target.value})} placeholder="Nome do estabelecimento"/><Field value={newVenue.city} onChange={event=>setNewVenue({...newVenue,city:event.target.value})} placeholder="Cidade"/><Textarea value={newVenue.description} onChange={event=>setNewVenue({...newVenue,description:event.target.value})} placeholder="Descrição"/><Button disabled={busy||newVenue.name.length<2} onClick={()=>void act(()=>api.createVenue(newVenue),"Novo estabelecimento criado.")}><Building2/> Criar unidade</Button></div></Card></div></>}
  <Card title="Modo TV"><div className="settings-callout"><MonitorPlay/><div><strong>Tela pública do estabelecimento</strong><p>Abra em uma TV, computador ou navegador integrado.</p><code>{base}/?tv={snapshot.venue.slug}</code></div><Button onClick={()=>window.open(`/?tv=${snapshot.venue.slug}`,"_blank")}>Abrir modo TV</Button></div></Card>
 </div>
}

